[[constraint]]
  name = "github.com/alexcesaro/statsd"
  version = "2.0.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.26"

[[constraint]]
  name = "github.com/blevesearch/bleve"
  version = "0.7.0"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/ghetzel/cli"
  version = "1.16.0"

[[constraint]]
  name = "github.com/ghetzel/diecast"
  version = ">=1.8.3"

[[constraint]]
  name = "github.com/ghetzel/go-stockutil"
  version = ">=1.5.39"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  name = "github.com/husobee/vestigo"
  version = "1.1.0"

[[constraint]]
  name = "github.com/jbenet/go-base58"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/jdxcode/netrc"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/orcaman/concurrent-map"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.3.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[prune]
  go-tests = true
  unused-packages = true
